### ISSUE TITLE
Different start/end dates for MPs in the biographical books and in matriklar 

### ISSUE THREAD

**Issue by fredrik1984** [swerik-project/riksdagen-persons#7]
According to Jan Teorell, there seems to be a problem with different MP start/end dates, which causes duplicate MPs on the same chair. Again, according to Jan, this could be because Swerik has used start/end dates from the biographical books, and the chair project from matriklarna. 

This is not a big issue for the Swerik project but it is worth taking a look at it at some point. 

@BobBorges do you have any take on this?

**Comment by BobBorges** [comment]
In the data set I generated for them, there are _both_ dates if there is a discrepancy between wikidata (assuming it's the same as in bio-books) info and martriklar. The tests run on the wikidata dates for consistency with the rest of the SWERIK project. If we want to resolve this properly, I guess we would need to double check dates with discrepancies and/or find a third source to verify before making edits to info that's on wikidata.

**Comment by fredrik1984** [comment]
Ok, good to know. I don't think this is a pressing issue, and I think this is work for the chair project

**Comment by BobBorges** [comment]
Closing this -- no task.
